import AppKit
import ChelkaCore
import UniformTypeIdentifiers

/// Разбирает содержимое буфера обмена в запись истории.
///
/// Здесь же живёт защита от самозацикливания: когда пользователь выбирает
/// запись из истории, мы сами кладём её в буфер — и монитор тут же увидел бы
/// «новое» содержимое.
enum PasteboardReader {

    /// Метка, которой помечаются собственные записи в буфер.
    /// Общепринятая договорённость менеджеров буфера обмена.
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Метка секретных данных: её ставят менеджеры паролей.
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    /// Метка «не сохранять в историю» — уважают все приличные менеджеры.
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")

    struct Reading {
        let payload: ClipboardPayload
        let preview: String
        let subtitle: String?
        let pixelWidth: Int?
        let pixelHeight: Int?
    }

    /// Причина, по которой содержимое буфера не попало в историю.
    enum Rejection: Equatable {
        case ownWrite
        case transient
        case concealed
        case blacklisted(String)
        case empty
        case tooLarge(Int)
    }

    enum Result: Equatable {
        case accepted(Reading)
        case rejected(Rejection)

        static func == (lhs: Result, rhs: Result) -> Bool {
            switch (lhs, rhs) {
            case (.rejected(let a), .rejected(let b)): return a == b
            case (.accepted(let a), .accepted(let b)): return a.payload == b.payload
            default: return false
            }
        }
    }

    static func read(
        _ pasteboard: NSPasteboard,
        sourceBundleID: String?,
        settings: ClipboardSettings
    ) -> Result {
        let types = Set(pasteboard.types ?? [])

        if types.contains(autoGeneratedType) { return .rejected(.ownWrite) }
        if types.contains(transientType) { return .rejected(.transient) }
        if settings.skipConcealed, types.contains(concealedType) { return .rejected(.concealed) }

        if let bundleID = sourceBundleID, settings.isBlacklisted(bundleID) {
            return .rejected(.blacklisted(bundleID))
        }

        guard let reading = extract(from: pasteboard) else { return .rejected(.empty) }

        let size = reading.payload.byteSize
        guard size <= ClipboardStore.maxPayloadBytes else { return .rejected(.tooLarge(size)) }

        return .accepted(reading)
    }

    /// Порядок разбора важен: скопированный из Finder файл содержит и путь,
    /// и текстовое представление, и иногда картинку-превью. Берём самое
    /// содержательное представление, а не первое попавшееся.
    private static func extract(from pasteboard: NSPasteboard) -> Reading? {
        if let files = readFileURLs(pasteboard) { return files }
        if let image = readImage(pasteboard) { return image }
        if let text = readText(pasteboard) { return text }
        return nil
    }

    // MARK: - Файлы

    private static func readFileURLs(_ pasteboard: NSPasteboard) -> Reading? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        guard let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
              !urls.isEmpty
        else { return nil }

        let preview: String
        let subtitle: String?

        if urls.count == 1, let url = urls.first {
            preview = url.lastPathComponent
            subtitle = url.deletingLastPathComponent().path
        } else {
            preview = "\(urls.count) \(pluralFiles(urls.count))"
            subtitle = urls.first?.deletingLastPathComponent().path
        }

        return Reading(
            payload: .files(urls),
            preview: preview,
            subtitle: subtitle,
            pixelWidth: nil,
            pixelHeight: nil
        )
    }

    // MARK: - Картинки

    private static func readImage(_ pasteboard: NSPasteboard) -> Reading? {
        // PNG предпочтительнее TIFF: тот же снимок в TIFF весит в разы больше.
        let candidates: [(NSPasteboard.PasteboardType, String)] = [
            (.png, UTType.png.identifier),
            (NSPasteboard.PasteboardType("public.jpeg"), UTType.jpeg.identifier),
            (.tiff, UTType.tiff.identifier),
        ]

        for (type, uti) in candidates {
            guard let data = pasteboard.data(forType: type), !data.isEmpty else { continue }
            let size = imagePixelSize(data)

            return Reading(
                payload: .image(data: data, uti: uti),
                preview: size.map { "Изображение \($0.width)×\($0.height)" } ?? "Изображение",
                subtitle: shortTypeName(uti) + " · " + formatBytes(data.count),
                pixelWidth: size?.width,
                pixelHeight: size?.height
            )
        }
        return nil
    }

    private static func imagePixelSize(_ data: Data) -> (width: Int, height: Int)? {
        guard let rep = NSBitmapImageRep(data: data) else { return nil }
        return (rep.pixelsWide, rep.pixelsHigh)
    }

    // MARK: - Текст

    private static func readText(_ pasteboard: NSPasteboard) -> Reading? {
        guard let string = pasteboard.string(forType: .string), !string.isEmpty else { return nil }

        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        return Reading(
            payload: .text(string),
            preview: previewText(from: trimmed),
            subtitle: textSubtitle(for: trimmed),
            pixelWidth: nil,
            pixelHeight: nil
        )
    }

    /// Превью в одну строку: переносы и лишние пробелы в списке только мешают.
    static func previewText(from string: String, limit: Int = 140) -> String {
        let collapsed = string
            .components(separatedBy: .whitespacesAndNewlines)
            .filter { !$0.isEmpty }
            .joined(separator: " ")

        guard collapsed.count > limit else { return collapsed }
        return String(collapsed.prefix(limit)) + "…"
    }

    static func textSubtitle(for string: String) -> String {
        if let host = linkHost(in: string) { return host }

        let lines = string.components(separatedBy: .newlines).count
        let characters = string.count
        return lines > 1 ? "\(characters) симв. · \(lines) строк" : "\(characters) симв."
    }

    /// Домен, если скопирована ссылка. Показывать «example.com» полезнее,
    /// чем «57 симв.».
    static func linkHost(in string: String) -> String? {
        let candidate = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !candidate.contains(" "), candidate.count < 2048 else { return nil }
        guard let url = URL(string: candidate), let host = url.host else { return nil }
        guard let scheme = url.scheme, ["http", "https", "ftp"].contains(scheme.lowercased()) else { return nil }
        return host
    }

    // MARK: - Форматирование

    static func formatBytes(_ bytes: Int) -> String {
        let formatter = ByteCountFormatter()
        formatter.countStyle = .file
        formatter.allowedUnits = [.useKB, .useMB]
        return formatter.string(fromByteCount: Int64(bytes))
    }

    static func shortTypeName(_ uti: String) -> String {
        UTType(uti)?.preferredFilenameExtension?.uppercased() ?? "IMG"
    }

    private static func pluralFiles(_ count: Int) -> String {
        let remainder100 = count % 100
        let remainder10 = count % 10

        if (11...14).contains(remainder100) { return "файлов" }
        switch remainder10 {
        case 1: return "файл"
        case 2, 3, 4: return "файла"
        default: return "файлов"
        }
    }
}
